apiVersion: v1
kind: Namespace
metadata:
  name: lakehouse-platform
  labels:
    app.kubernetes.io/part-of: lakehouse-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: lakehouse-jobs
  labels:
    app.kubernetes.io/part-of: lakehouse-platform
    purpose: spark-job-execution

